name: build

on:
  workflow_dispatch:
  push:
    branches: ['main']
  pull_request:
    branches: ['**']

env:
  NEXT_TELEMETRY_DISABLED: 1

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.next/cache
            ${{ github.workspace }}/node_modules
          key: |
            ${{ runner.os }}-nextjs-${{ hashFiles('bun.lockb') }}-${{ hashFiles('*.js', '*.json', '**/*.mdx', '**/*.ts', '**/*.tsx', 'styles/globals.css') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('bun.lockb') }}-
      - name: setup bun
        uses: oven-sh/setup-bun@v1
      - name: install
        run: bun install --production --frozen-lockfile
      - name: lint
        run: bun run lint
      - name: build
        run: bun run build
      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out/
  deploy:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true && github.base_ref == 'main')
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: deploy to github pages
        uses: actions/deploy-pages@v4
        id: deployment
